name: paleoPCA-Cookbook
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - pip
  - pandas
  - xarray
  - s3fs
  - fsspec
  - numpy
  - cartopy
  - matplotlib
  - eofs
  - nc-time-axis
  - h5netcdf
  - pip:
    - pyleoclim
